<?php

namespace Database\Seeders;

use App\Models\InternationalPackage;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EsimPackageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $packages = [
            // GCC Limited Data Packages - 7 Days
            [
                'type_en' => 'Limited Data',
                'type_ar' => 'بيانات محدودة',
                'type_zh' => '有限数据',
                'region_en' => 'GCC',
                'region_ar' => 'دول مجلس التعاون',
                'region_zh' => 'GCC国家',
                'title_en' => '1 GB - 7 Days',
                'title_ar' => '1 جيجابايت - 7 أيام',
                'title_zh' => '1GB - 7天',
                'description_en' => 'eSIM for GCC. Stay connected with high-speed data across GCC countries. No physical SIM needed - instant activation upon arrival.',
                'description_ar' => 'eSIM لدول الخليج. ابقَ متصلاً مع بيانات عالية السرعة عبر دول الخليج. بدون بطاقة SIM فعلية - تفعيل فوري عند الوصول.',
                'description_zh' => 'GCC eSIM。通过GCC国家保持高速数据连接。无需物理SIM卡 - 到达后立即激活。',
                'data_amount' => '1 GB',
                'plan_type' => 'limited_data',
                'duration_en' => '7 Days',
                'duration_ar' => '7 أيام',
                'duration_zh' => '7天',
                'price' => 6.00,
                'starting_price' => '$5.00',
                'discount' => null,
                'package_code' => 'GCC-1GB-7Days',
                'networks' => ['Zain', 'Etisalat', 'Mobily', 'du'],
                'supported_countries' => ['Saudi Arabia', 'UAE', 'Kuwait', 'Qatar', 'Bahrain', 'Oman'],
                'supported_countries_count' => 6,
                'hotspot_tethering' => true,
                'rechargeability' => true,
                'features_en' => [
                    'High speed and stable connection',
                    'Keep your WhatsApp number on your cellphone',
                    'Receive your QR code and surf instantly',
                    'Connect to the best network',
                ],
                'features_ar' => [
                    'اتصال سريع وثابت',
                    'احتفظ برقم واتساب على هاتفك',
                    'استقبل رمز QR واستمتع بالتصفح فوراً',
                    'اتصل بأفضل شبكة',
                ],
                'features_zh' => [
                    '高速稳定连接',
                    '在手机上保留 WhatsApp 号码',
                    '接收二维码并立即上网',
                    '连接到最佳网络',
                ],
                'highlight_en' => 'Instant Activation',
                'highlight_ar' => 'تفعيل فوري',
                'highlight_zh' => '即时激活',
                'active' => true,
            ],
            // GCC Limited Data - 15 Days
            [
                'type_en' => 'Limited Data',
                'type_ar' => 'بيانات محدودة',
                'type_zh' => '有限数据',
                'region_en' => 'GCC',
                'region_ar' => 'دول مجلس التعاون',
                'region_zh' => 'GCC国家',
                'title_en' => '1.5 GB - 15 Days',
                'title_ar' => '1.5 جيجابايت - 15 يوماً',
                'title_zh' => '1.5GB - 15天',
                'description_en' => 'eSIM for GCC. Extended coverage for your extended stay.',
                'description_ar' => 'eSIM لدول الخليج. تغطية موسعة لإقامتك الممتدة.',
                'description_zh' => 'GCC eSIM。为您的延期停留提供扩展覆盖。',
                'data_amount' => '1.5 GB',
                'plan_type' => 'limited_data',
                'duration_en' => '15 Days',
                'duration_ar' => '15 يوم',
                'duration_zh' => '15天',
                'price' => 9.00,
                'starting_price' => '$5.00',
                'discount' => null,
                'package_code' => 'GCC-1.5GB-15Days',
                'networks' => ['Zain', 'Etisalat', 'Mobily', 'du'],
                'supported_countries' => ['Saudi Arabia', 'UAE', 'Kuwait', 'Qatar', 'Bahrain', 'Oman'],
                'supported_countries_count' => 6,
                'hotspot_tethering' => true,
                'rechargeability' => true,
                'features_en' => ['High speed and stable connection', 'No physical SIM needed', 'Easy to set up and activate'],
                'features_ar' => ['اتصال سريع وثابت', 'بدون بطاقة SIM فعلية', 'سهل الإعداد والتفعيل'],
                'features_zh' => ['高速稳定连接', '无需物理SIM卡', '易于设置和激活'],
                'highlight_en' => 'Best Value',
                'highlight_ar' => 'أفضل قيمة',
                'highlight_zh' => '最佳价值',
                'active' => true,
            ],
            // GCC Unlimited Data - 30 Days
            [
                'type_en' => 'Unlimited Data',
                'type_ar' => 'بيانات غير محدودة',
                'type_zh' => '无限数据',
                'region_en' => 'GCC',
                'region_ar' => 'دول مجلس التعاون',
                'region_zh' => 'GCC国家',
                'title_en' => '3 GB - 30 Days',
                'title_ar' => '3 جيجابايت - 30 يوماً',
                'title_zh' => '3GB - 30天',
                'description_en' => 'eSIM for GCC. Perfect for a month-long stay with continuous connectivity.',
                'description_ar' => 'eSIM لدول الخليج. مثالي لإقامة شهر كامل مع اتصال مستمر.',
                'description_zh' => 'GCC eSIM。非常适合为期一个月的停留，具有持续连接。',
                'data_amount' => '3 GB',
                'plan_type' => 'unlimited_data',
                'duration_en' => '30 Days',
                'duration_ar' => '30 يوم',
                'duration_zh' => '30天',
                'price' => 22.50,
                'starting_price' => '$5.00',
                'discount' => null,
                'package_code' => 'GCC-3GB-30Days',
                'networks' => ['Zain', 'Etisalat', 'Mobily', 'du'],
                'supported_countries' => ['Saudi Arabia', 'UAE', 'Kuwait', 'Qatar', 'Bahrain', 'Oman'],
                'supported_countries_count' => 6,
                'hotspot_tethering' => true,
                'rechargeability' => true,
                'features_en' => [
                    'High speed and stable connection',
                    'Keep your WhatsApp number on your cellphone',
                    'Receive your QR code and surf instantly',
                    'Forget about roaming or searching for public WiFi networks',
                ],
                'features_ar' => [
                    'اتصال سريع وثابت',
                    'احتفظ برقم واتساب على هاتفك',
                    'استقبل رمز QR واستمتع بالتصفح فوراً',
                    'انسَ عن التجوال أو البحث عن شبكات WiFi عامة',
                ],
                'features_zh' => [
                    '高速稳定连接',
                    '在手机上保留 WhatsApp 号码',
                    '接收二维码并立即上网',
                    '忘记漫游或搜索公共 WiFi 网络',
                ],
                'highlight_en' => 'Most Popular',
                'highlight_ar' => 'الأكثر شهرة',
                'highlight_zh' => '最受欢迎',
                'active' => true,
            ],
            // GCC Unlimited Data - 60 Days
            [
                'type_en' => 'Unlimited Data',
                'type_ar' => 'بيانات غير محدودة',
                'type_zh' => '无限数据',
                'region_en' => 'GCC',
                'region_ar' => 'دول مجلس التعاون',
                'region_zh' => 'GCC国家',
                'title_en' => '10 GB - 60 Days',
                'title_ar' => '10 جيجابايت - 60 يوماً',
                'title_zh' => '10GB - 60天',
                'description_en' => 'eSIM for GCC. Extended data for extended travels.',
                'description_ar' => 'eSIM لدول الخليج. بيانات موسعة للسفر الممتد.',
                'description_zh' => 'GCC eSIM。为延期旅行提供扩展数据。',
                'data_amount' => '10 GB',
                'plan_type' => 'unlimited_data',
                'duration_en' => '60 Days',
                'duration_ar' => '60 يوم',
                'duration_zh' => '60天',
                'price' => 55.00,
                'starting_price' => '$5.00',
                'discount' => null,
                'package_code' => 'GCC-10GB-60Days',
                'networks' => ['Zain', 'Etisalat', 'Mobily', 'du'],
                'supported_countries' => ['Saudi Arabia', 'UAE', 'Kuwait', 'Qatar', 'Bahrain', 'Oman'],
                'supported_countries_count' => 6,
                'hotspot_tethering' => true,
                'rechargeability' => true,
                'features_en' => ['High speed and stable connection', 'Easy to set up and activate', 'Available for long-term stays'],
                'features_ar' => ['اتصال سريع وثابت', 'سهل الإعداد والتفعيل', 'متاح للإقامات الطويلة'],
                'features_zh' => ['高速稳定连接', '易于设置和激活', '可用于长期停留'],
                'highlight_en' => 'Long Stay',
                'highlight_ar' => 'إقامة طويلة',
                'highlight_zh' => '长期停留',
                'active' => true,
            ],
        ];

        foreach ($packages as $package) {
            InternationalPackage::create($package);
        }
    }
}
