<?php

namespace Database\Seeders;

use App\Models\TourismDestination;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TourismDestinationsSeeder extends Seeder
{
    private $commonContactInfo = [
        'address_en' => 'Al Rabwa, Jeddah',
        'address_ar' => 'الربوة، جدة',
        'phone' => '0547305060',
        'whatsapp' => '966547305060',
        'email' => 'info@tilalr.com',
    ];

    private $commonPaymentMethods = [
        [
            'name_en' => 'Al Rajhi Bank',
            'name_ar' => 'مصرف الراجحي',
            'account_no' => '11111111',
            'iban' => 'SA1111111111111',
        ],
        [
            'name_en' => 'STC Pay',
            'name_ar' => 'إس تي سي باي',
            'account_no' => '22222222',
            'iban' => 'SA2222222222222',
        ],
    ];

    private $commonNotIncludes = [
        'en' => ['International flight', 'Visa', 'Travel insurance'],
        'ar' => ['الرحلات الدولية', 'التأشيرة', 'تأمين السفر'],
    ];

    public function run(): void
    {
        $destinations = [
            // ===== EUROPE =====
            [
                'title_en' => 'Britain & Ireland Tour',
                'title_ar' => 'جولة بريطانيا وأيرلندا',
                'description_en' => 'Stunning scenery, pretty villages, ancient sights, and exciting cities this Britain and Ireland tour offers all of this and more.',
                'description_ar' => 'مناظر خلابة، قرى جميلة، معالم قديمة، ومدن مثيرة - تقدم هذه الجولة في بريطانيا وأيرلندا كل هذا وأكثر.',
                'long_description_en' => 'Stunning scenery, pretty villages, ancient sights, and exciting cities this Britain and Ireland tour offers all of this and more. Your tour starts in Dublin, Ireland\'s fun capital, ends in London, England\'s exciting capital, and overnights along the way in Ennis, Killarney, Tramore, and Cardiff, the capital of Wales.',
                'long_description_ar' => 'مناظر خلابة، قرى جميلة، معالم قديمة، ومدن مثيرة - تقدم هذه الجولة في بريطانيا وأيرلندا كل هذا وأكثر. تبدأ جولتك في دبلن، عاصمة المرح في أيرلندا، وتنتهي في لندن، عاصمة إنجلترا المثيرة، مع ليالي في إينيس وكيلارني وترامور وكارديف عاصمة ويلز.',
                'location_en' => 'Britain & Ireland',
                'location_ar' => 'بريطانيا وأيرلندا',
                'duration_en' => '9 Days',
                'duration_ar' => '٩ أيام',
                'price' => '4100',
                'rating' => 4.8,
                'image' => '01KW8E20JEXP5P7280VW66CV64.jpeg',
                'slug' => 'britain-ireland-tour',
                'region' => 'europe',
                'active' => true,
                'features_en' => ['Hotel', 'Full English breakfast daily', '2 dinners with choice of menus', 'Sightseeing tours'],
                'features_ar' => ['فندق', 'إفطار إنجليزي كامل يومياً', 'وجبتي عشاء مع قوائم اختيار', 'جولات سياحية'],
                'includes_en' => ['Accommodation', 'Daily breakfast', 'Selected dinners', 'Guided tours', 'Transportation'],
                'includes_ar' => ['الإقامة', 'إفطار يومي', 'وجبات عشاء مختارة', 'جولات مرشدة', 'النقل'],
                'not_includes_en' => $this->commonNotIncludes['en'],
                'not_includes_ar' => $this->commonNotIncludes['ar'],
                'basic_info' => [
                    'trip_code' => 'AB9040',
                    'days_num' => 9,
                    'destination_name_en' => 'Britain & Ireland',
                    'destination_name_ar' => 'بريطانيا وأيرلندا',
                    'available_to' => '30-09-2024',
                    'double_room_en' => 'Double Room',
                    'double_room_ar' => 'غرفة مزدوجة',
                    'double_room_price' => 4100,
                    'single_room_en' => 'Single Room',
                    'single_room_ar' => 'غرفة فردية',
                    'single_room_price' => 8250,
                    'trip_type_en' => 'International',
                    'trip_type_ar' => 'دولي',
                    'meal_plan_en' => 'Half Board',
                    'meal_plan_ar' => 'نصف إقامة',
                    'transport_en' => 'Tourist Bus',
                    'transport_ar' => 'حافلة سياحية',
                ],
                'contact_info' => $this->commonContactInfo,
                'payment_methods' => $this->commonPaymentMethods,
            ],

            // Poland
            [
                'title_en' => 'Poland Discovery Tour',
                'title_ar' => 'جولة اكتشاف بولندا',
                'description_en' => 'A rich cultural heritage, fascinating history, and beautiful landscapes make Poland an interesting place to discover.',
                'description_ar' => 'التراث الثقافي الغني والتاريخ الرائع والمناظر الطبيعية الجميلة تجعل بولندا مكانًا مثيرًا للاكتشاف.',
                'long_description_en' => 'A rich cultural heritage, fascinating history, and beautiful landscapes make Poland an interesting place to discover. On this Poland tour, you\'ll spend two nights in Warsaw and Gdansk, three nights in Kraków, and one night in Poznan.',
                'long_description_ar' => 'التراث الثقافي الغني والتاريخ الرائع والمناظر الطبيعية الجميلة تجعل بولندا مكانًا مثيرًا للاكتشاف. في هذه الجولة البولندية، ستقضي ليلتين في وارسو وغدانسك، وثلاث ليالٍ في كراكوف، وليلة واحدة في بوزنان.',
                'location_en' => 'Poland',
                'location_ar' => 'بولندا',
                'duration_en' => '9 Days',
                'duration_ar' => '٩ أيام',
                'price' => '3200',
                'rating' => 4.6,
                'image' => '5.jpg',
                'slug' => 'poland-discovery',
                'region' => 'europe',
                'active' => true,
                'features_en' => ['Hotel', 'Breakfast daily', 'Sightseeing tours', 'Tour guide'],
                'features_ar' => ['فندق', 'إفطار يومي', 'جولات سياحية', 'مرشد سياحي'],
                'includes_en' => ['Accommodation', 'Daily breakfast', 'Guided tours', 'Professional guide'],
                'includes_ar' => ['الإقامة', 'إفطار يومي', 'جولات مرشدة', 'مرشد محترف'],
                'not_includes_en' => $this->commonNotIncludes['en'],
                'not_includes_ar' => $this->commonNotIncludes['ar'],
                'basic_info' => [
                    'trip_code' => '6080',
                    'days_num' => 9,
                    'destination_name_en' => 'Poland',
                    'destination_name_ar' => 'بولندا',
                    'available_to' => '07-09-2024',
                    'double_room_en' => 'Double Room',
                    'double_room_ar' => 'غرفة مزدوجة',
                    'double_room_price' => 3200,
                    'single_room_en' => 'Single Room',
                    'single_room_ar' => 'غرفة فردية',
                    'single_room_price' => 6400,
                    'trip_type_en' => 'International',
                    'trip_type_ar' => 'دولي',
                    'meal_plan_en' => 'Bed & Breakfast',
                    'meal_plan_ar' => 'مبيت وإفطار',
                    'transport_en' => 'Minibus',
                    'transport_ar' => 'حافلة صغيرة',
                ],
                'contact_info' => $this->commonContactInfo,
                'payment_methods' => $this->commonPaymentMethods,
            ],

            // Norway
            [
                'title_en' => 'Norwegian Fjords Adventure',
                'title_ar' => 'مغامرة المضايق النرويجية',
                'description_en' => 'Your affordable guided tour of Norway focuses on the country\'s intact natural beauty with its glistening mountains, fjords, waterfalls, and glaciers.',
                'description_ar' => 'تركز جولتك المصحوبة بمرشد في النرويج على الجمال الطبيعي السليم للبلاد مع جبالها اللامعة ومضايقها وشلالاتها وأنهارها الجليدية.',
                'long_description_en' => 'Experience the breathtaking beauty of Norway\'s fjords. This tour takes you through stunning landscapes, charming coastal villages, and majestic mountains. Enjoy a fjord cruise, scenic train rides, and breathtaking views.',
                'long_description_ar' => 'اختبر الجمال الخلاب لمضايق النرويج. تأخذك هذه الجولة عبر مناظر طبيعية مذهلة وقرى ساحلية ساحرة وجبال مهيبة. استمتع برحلة بحرية في المضايق ورحلات قطار خلابة وإطلالات رائعة.',
                'location_en' => 'Norway',
                'location_ar' => 'النرويج',
                'duration_en' => '11 Days',
                'duration_ar' => '١١ يومًا',
                'price' => '3800',
                'rating' => 4.9,
                'image' => 'norway.jpg',
                'slug' => 'norway-fjords',
                'region' => 'europe',
                'active' => true,
                'features_en' => ['Hotel', 'Breakfast daily', 'Fjord cruise', 'Train journey', 'Mountain views'],
                'features_ar' => ['فندق', 'إفطار يومي', 'رحلة بحرية في المضايق', 'رحلة قطار', 'إطلالات جبلية'],
                'includes_en' => ['Accommodation', 'Daily breakfast', 'Fjord cruise tickets', 'Train tickets', 'Professional guide'],
                'includes_ar' => ['الإقامة', 'إفطار يومي', 'تذاكر رحلة المضايق', 'تذاكر القطار', 'مرشد محترف'],
                'not_includes_en' => $this->commonNotIncludes['en'],
                'not_includes_ar' => $this->commonNotIncludes['ar'],
                'basic_info' => [
                    'trip_code' => 'NV7890',
                    'days_num' => 11,
                    'destination_name_en' => 'Norway',
                    'destination_name_ar' => 'النرويج',
                    'available_to' => '15-10-2024',
                    'double_room_en' => 'Double Room',
                    'double_room_ar' => 'غرفة مزدوجة',
                    'double_room_price' => 3800,
                    'single_room_en' => 'Single Room',
                    'single_room_ar' => 'غرفة فردية',
                    'single_room_price' => 7600,
                    'trip_type_en' => 'International',
                    'trip_type_ar' => 'دولي',
                    'meal_plan_en' => 'Half Board',
                    'meal_plan_ar' => 'نصف إقامة',
                    'transport_en' => 'Train & Boat',
                    'transport_ar' => 'قطار وقارب',
                ],
                'contact_info' => $this->commonContactInfo,
                'payment_methods' => $this->commonPaymentMethods,
            ],

            // Germany
            [
                'title_en' => 'Highlights of Germany',
                'title_ar' => 'معالم ألمانيا البارزة',
                'description_en' => 'Spectacular scenery, medieval towns, fairy-tale castles, a fascinating history, and world-class beer...this is Germany!',
                'description_ar' => 'مناظر خلابة، مدن من العصور الوسطى، قلاع خرافية، تاريخ رائع، وبيرة عالمية... هذه هي ألمانيا!',
                'long_description_en' => 'Discover the highlights of Germany on this comprehensive tour. Visit historic cities like Berlin, Munich, and Heidelberg. Explore medieval towns, fairy-tale castles along the Rhine, and experience the rich culture and traditions of Germany.',
                'long_description_ar' => 'اكتشف معالم ألمانيا البارزة في هذه الجولة الشاملة. قم بزيارة المدن التاريخية مثل برلين وميونيخ وهايدلبرغ. استكشف المدن من العصور الوسطى والقلاع الخرافية على نهر الراين واختبر الثقافة والتقاليد الغنية لألمانيا.',
                'location_en' => 'Germany',
                'location_ar' => 'ألمانيا',
                'duration_en' => '12 Days',
                'duration_ar' => '١٢ يومًا',
                'price' => '3500',
                'rating' => 4.7,
                'image' => 'germany.jpg',
                'slug' => 'highlights-of-germany',
                'region' => 'europe',
                'active' => true,
                'features_en' => ['Hotel', 'Breakfast daily', 'Rhine cruise', 'Castle visits', 'City tours'],
                'features_ar' => ['فندق', 'إفطار يومي', 'رحلة بحرية على نهر الراين', 'زيارات القلاع', 'جولات المدينة'],
                'includes_en' => ['Accommodation', 'Daily breakfast', 'Rhine cruise', 'Entrance fees to castles', 'Professional guide'],
                'includes_ar' => ['الإقامة', 'إفطار يومي', 'رحلة نهر الراين', 'رسوم دخول القلاع', 'مرشد محترف'],
                'not_includes_en' => $this->commonNotIncludes['en'],
                'not_includes_ar' => $this->commonNotIncludes['ar'],
                'basic_info' => [
                    'trip_code' => 'GR5678',
                    'days_num' => 12,
                    'destination_name_en' => 'Germany',
                    'destination_name_ar' => 'ألمانيا',
                    'available_to' => '20-11-2024',
                    'double_room_en' => 'Double Room',
                    'double_room_ar' => 'غرفة مزدوجة',
                    'double_room_price' => 3500,
                    'single_room_en' => 'Single Room',
                    'single_room_ar' => 'غرفة فردية',
                    'single_room_price' => 7000,
                    'trip_type_en' => 'International',
                    'trip_type_ar' => 'دولي',
                    'meal_plan_en' => 'Bed & Breakfast',
                    'meal_plan_ar' => 'مبيت وإفطار',
                    'transport_en' => 'Tourist Bus',
                    'transport_ar' => 'حافلة سياحية',
                ],
                'contact_info' => $this->commonContactInfo,
                'payment_methods' => $this->commonPaymentMethods,
            ],

            // Switzerland
            [
                'title_en' => 'Switzerland Package',
                'title_ar' => 'باقة سويسرا',
                'description_en' => 'This Scenic Switzerland by Train tour is the perfect way to see Switzerland breathtaking mountains, charming mountain resorts, fascinating old towns, and beautiful lakes.',
                'description_ar' => 'هذه الجولة الخلابة في سويسرا بالقطار هي الطريقة المثالية لرؤية جبال سويسرا الخلابة ومنتجعات الجبال الساحرة والمدن القديمة الرائعة والبحيرات الجميلة.',
                'long_description_en' => 'Experience the best of Switzerland on this scenic train tour. Journey through the Alps, visit charming villages, enjoy stunning lake views, and explore historic cities like Lucerne and Interlaken. This tour offers the perfect blend of nature and culture.',
                'long_description_ar' => 'اختبر أفضل ما في سويسرا في هذه الجولة الخلابة بالقطار. سافر عبر جبال الألب، وقم بزيارة القرى الساحرة، واستمتع بإطلالات بحيرات رائعة، واستكشف المدن التاريخية مثل لوسيرن وإنترلاكن. تقدم هذه الجولة مزيجًا مثاليًا من الطبيعة والثقافة.',
                'location_en' => 'Switzerland',
                'location_ar' => 'سويسرا',
                'duration_en' => '9 Days',
                'duration_ar' => '٩ أيام',
                'price' => '4200',
                'rating' => 4.9,
                'image' => 'switzerland.jpg',
                'slug' => 'switzerland-package',
                'region' => 'europe',
                'active' => true,
                'features_en' => ['Hotel', 'Buffet breakfasts daily', '3 dinners', 'Train tours', 'Mountain excursions'],
                'features_ar' => ['فندق', 'إفطار بوفيه يومي', '٣ وجبات عشاء', 'جولات بالقطار', 'رحلات جبلية'],
                'includes_en' => ['Accommodation', 'Buffet breakfast daily', '3 dinners', 'Train tickets', 'Mountain excursions', 'Professional guide'],
                'includes_ar' => ['الإقامة', 'إفطار بوفيه يومي', '٣ وجبات عشاء', 'تذاكر القطار', 'رحلات جبلية', 'مرشد محترف'],
                'not_includes_en' => $this->commonNotIncludes['en'],
                'not_includes_ar' => $this->commonNotIncludes['ar'],
                'basic_info' => [
                    'trip_code' => 'CH9012',
                    'days_num' => 9,
                    'destination_name_en' => 'Switzerland',
                    'destination_name_ar' => 'سويسرا',
                    'available_to' => '05-12-2024',
                    'double_room_en' => 'Double Room',
                    'double_room_ar' => 'غرفة مزدوجة',
                    'double_room_price' => 4200,
                    'single_room_en' => 'Single Room',
                    'single_room_ar' => 'غرفة فردية',
                    'single_room_price' => 8400,
                    'trip_type_en' => 'International',
                    'trip_type_ar' => 'دولي',
                    'meal_plan_en' => 'Half Board',
                    'meal_plan_ar' => 'نصف إقامة',
                    'transport_en' => 'Train',
                    'transport_ar' => 'قطار',
                ],
                'contact_info' => $this->commonContactInfo,
                'payment_methods' => $this->commonPaymentMethods,
            ],

            // ===== ASIA =====
            [
                'title_en' => 'Thailand Beach Getaway',
                'title_ar' => 'رحلة شاطئ تايلاند',
                'description_en' => 'Experience the beautiful beaches and rich culture of Thailand.',
                'description_ar' => 'اختبر الشواطئ الجميلة والثقافة الغنية لتايلاند.',
                'long_description_en' => 'Escape to the tropical paradise of Thailand. Visit stunning beaches like Phuket and Krabi, explore vibrant Bangkok, and immerse yourself in the rich Thai culture. Enjoy water activities, delicious cuisine, and warm hospitality.',
                'long_description_ar' => 'اهرب إلى الجنة الاستوائية في تايلاند. قم بزيارة الشواطئ الخلابة مثل فوكيت وكرابي، واستكشف بانكوك النابضة بالحياة، وانغمس في الثقافة التايلاندية الغنية. استمتع بالأنشطة المائية والمأكولات اللذيذة وكرم الضيافة.',
                'location_en' => 'Thailand',
                'location_ar' => 'تايلاند',
                'duration_en' => '7 Days',
                'duration_ar' => '٧ أيام',
                'price' => '2000',
                'rating' => 4.8,
                'image' => 'thailand.jpg',
                'slug' => 'thailand-getaway',
                'region' => 'asia',
                'active' => true,
                'features_en' => ['Hotel', 'Breakfast daily', 'Island tours', 'Water activities', 'City tours'],
                'features_ar' => ['فندق', 'إفطار يومي', 'جولات الجزر', 'الأنشطة المائية', 'جولات المدينة'],
                'includes_en' => ['Accommodation', 'Daily breakfast', 'Island tours', 'Water activities', 'Professional guide'],
                'includes_ar' => ['الإقامة', 'إفطار يومي', 'جولات الجزر', 'الأنشطة المائية', 'مرشد محترف'],
                'not_includes_en' => $this->commonNotIncludes['en'],
                'not_includes_ar' => $this->commonNotIncludes['ar'],
                'basic_info' => [
                    'trip_code' => 'TH3456',
                    'days_num' => 7,
                    'destination_name_en' => 'Thailand',
                    'destination_name_ar' => 'تايلاند',
                    'available_to' => '15-08-2024',
                    'double_room_en' => 'Double Room',
                    'double_room_ar' => 'غرفة مزدوجة',
                    'double_room_price' => 2000,
                    'single_room_en' => 'Single Room',
                    'single_room_ar' => 'غرفة فردية',
                    'single_room_price' => 4000,
                    'trip_type_en' => 'International',
                    'trip_type_ar' => 'دولي',
                    'meal_plan_en' => 'Bed & Breakfast',
                    'meal_plan_ar' => 'مبيت وإفطار',
                    'transport_en' => 'Minibus & Boat',
                    'transport_ar' => 'حافلة صغيرة وقارب',
                ],
                'contact_info' => $this->commonContactInfo,
                'payment_methods' => $this->commonPaymentMethods,
            ],

            // ===== AFRICA =====
            [
                'title_en' => 'Morocco Discovery Tour',
                'title_ar' => 'جولة اكتشاف المغرب',
                'description_en' => 'Explore the vibrant culture, stunning architecture, and delicious cuisine of Morocco.',
                'description_ar' => 'استكشف الثقافة النابضة بالحياة والهندسة المعمارية المذهلة والمأكولات اللذيذة في المغرب.',
                'long_description_en' => 'Discover the magic of Morocco on this comprehensive tour. Visit imperial cities like Marrakech, Fes, and Rabat. Explore the Sahara Desert, experience traditional souks, and enjoy the rich cultural heritage of this fascinating country.',
                'long_description_ar' => 'اكتشف سحر المغرب في هذه الجولة الشاملة. قم بزيارة المدن الإمبراطورية مثل مراكش وفاس والرباط. استكشف الصحراء الكبرى، واختبر الأسواق التقليدية، واستمتع بالتراث الثقافي الغني لهذا البلد الرائع.',
                'location_en' => 'Morocco',
                'location_ar' => 'المغرب',
                'duration_en' => '10 Days',
                'duration_ar' => '١٠ أيام',
                'price' => '2600',
                'rating' => 4.8,
                'image' => 'morocco.jpg',
                'slug' => 'morocco-discovery',
                'region' => 'africa',
                'active' => true,
                'features_en' => ['Hotel', 'Breakfast daily', 'City tours', 'Desert excursion', 'Cultural experiences'],
                'features_ar' => ['فندق', 'إفطار يومي', 'جولات المدينة', 'رحلة صحراوية', 'تجارب ثقافية'],
                'includes_en' => ['Accommodation', 'Daily breakfast', 'City tours', 'Desert excursion', 'Professional guide'],
                'includes_ar' => ['الإقامة', 'إفطار يومي', 'جولات المدينة', 'رحلة صحراوية', 'مرشد محترف'],
                'not_includes_en' => $this->commonNotIncludes['en'],
                'not_includes_ar' => $this->commonNotIncludes['ar'],
                'basic_info' => [
                    'trip_code' => 'MO7890',
                    'days_num' => 10,
                    'destination_name_en' => 'Morocco',
                    'destination_name_ar' => 'المغرب',
                    'available_to' => '25-09-2024',
                    'double_room_en' => 'Double Room',
                    'double_room_ar' => 'غرفة مزدوجة',
                    'double_room_price' => 2600,
                    'single_room_en' => 'Single Room',
                    'single_room_ar' => 'غرفة فردية',
                    'single_room_price' => 5200,
                    'trip_type_en' => 'International',
                    'trip_type_ar' => 'دولي',
                    'meal_plan_en' => 'Half Board',
                    'meal_plan_ar' => 'نصف إقامة',
                    'transport_en' => 'Tourist Bus & 4x4',
                    'transport_ar' => 'حافلة سياحية ودفع رباعي',
                ],
                'contact_info' => $this->commonContactInfo,
                'payment_methods' => $this->commonPaymentMethods,
            ],

            // ===== AUSTRALIA & NEW ZEALAND =====
            [
                'title_en' => 'Australia Adventure Tour',
                'title_ar' => 'جولة مغامرة أستراليا',
                'description_en' => 'Discover the stunning landscapes and unique wildlife of Australia.',
                'description_ar' => 'اكتشف المناظر الطبيعية الخلابة والحياة البرية الفريدة في أستراليا.',
                'long_description_en' => 'Explore the diverse landscapes of Australia. Visit iconic cities like Sydney and Melbourne, discover the Great Barrier Reef, explore the Outback, and encounter unique wildlife. This tour offers an unforgettable Australian adventure.',
                'long_description_ar' => 'استكشف المناظر الطبيعية المتنوعة في أستراليا. قم بزيارة المدن الأيقونية مثل سيدني وملبورن، واكتشف الحاجز المرجاني العظيم، واستكشف المناطق النائية، وتعرف على الحياة البرية الفريدة. تقدم هذه الجولة مغامرة أسترالية لا تنسى.',
                'location_en' => 'Australia',
                'location_ar' => 'أستراليا',
                'duration_en' => '12 Days',
                'duration_ar' => '١٢ يومًا',
                'price' => '4500',
                'rating' => 4.9,
                'image' => 'datacenter.png',
                'slug' => 'australia-adventure',
                'region' => 'australia',
                'active' => true,
                'features_en' => ['Hotel', 'Breakfast daily', 'Wildlife tours', 'City sightseeing', 'Great Barrier Reef'],
                'features_ar' => ['فندق', 'إفطار يومي', 'جولات الحياة البرية', 'جولات المدينة', 'الحاجز المرجاني العظيم'],
                'includes_en' => ['Accommodation', 'Daily breakfast', 'Wildlife tours', 'City tours', 'Great Barrier Reef trip', 'Professional guide'],
                'includes_ar' => ['الإقامة', 'إفطار يومي', 'جولات الحياة البرية', 'جولات المدينة', 'رحلة الحاجز المرجاني العظيم', 'مرشد محترف'],
                'not_includes_en' => $this->commonNotIncludes['en'],
                'not_includes_ar' => $this->commonNotIncludes['ar'],
                'basic_info' => [
                    'trip_code' => 'AU1234',
                    'days_num' => 12,
                    'destination_name_en' => 'Australia',
                    'destination_name_ar' => 'أستراليا',
                    'available_to' => '10-11-2024',
                    'double_room_en' => 'Double Room',
                    'double_room_ar' => 'غرفة مزدوجة',
                    'double_room_price' => 4500,
                    'single_room_en' => 'Single Room',
                    'single_room_ar' => 'غرفة فردية',
                    'single_room_price' => 9000,
                    'trip_type_en' => 'International',
                    'trip_type_ar' => 'دولي',
                    'meal_plan_en' => 'Bed & Breakfast',
                    'meal_plan_ar' => 'مبيت وإفطار',
                    'transport_en' => 'Coach & Boat',
                    'transport_ar' => 'حافلة وقارب',
                ],
                'contact_info' => $this->commonContactInfo,
                'payment_methods' => $this->commonPaymentMethods,
            ],

            // ===== AMERICA =====
            [
                'title_en' => 'USA East Coast Explorer',
                'title_ar' => 'جولة استكشاف الساحل الشرقي للولايات المتحدة',
                'description_en' => 'Discover the iconic cities and stunning landscapes of America\'s East Coast.',
                'description_ar' => 'اكتشف المدن الأيقونية والمناظر الطبيعية الخلابة في الساحل الشرقي لأمريكا.',
                'long_description_en' => 'From the bustling streets of New York City to the historic charm of Boston, this tour takes you through America\'s most iconic East Coast destinations. Visit Washington D.C., Philadelphia, and experience the vibrant culture of the United States.',
                'long_description_ar' => 'من شوارع نيويورك الصاخبة إلى سحر بوسطن التاريخي، تأخذك هذه الجولة عبر أشهر الوجهات في الساحل الشرقي لأمريكا. قم بزيارة واشنطن العاصمة وفيلادلفيا واختبر الثقافة النابضة بالحياة في الولايات المتحدة.',
                'location_en' => 'USA East Coast',
                'location_ar' => 'الساحل الشرقي للولايات المتحدة',
                'duration_en' => '10 Days',
                'duration_ar' => '١٠ أيام',
                'price' => '4800',
                'rating' => 4.8,
                'image' => 'usa.jpg',
                'slug' => 'usa-east-coast',
                'region' => 'america',
                'active' => true,
                'features_en' => ['Hotel', 'Breakfast daily', 'City tours', 'Museum visits', 'Guided tours'],
                'features_ar' => ['فندق', 'إفطار يومي', 'جولات المدينة', 'زيارات المتاحف', 'جولات مرشدة'],
                'includes_en' => ['Accommodation', 'Daily breakfast', 'City tours', 'Museum entrance fees', 'Professional guide', 'Transportation'],
                'includes_ar' => ['الإقامة', 'إفطار يومي', 'جولات المدينة', 'رسوم دخول المتاحف', 'مرشد محترف', 'النقل'],
                'not_includes_en' => $this->commonNotIncludes['en'],
                'not_includes_ar' => $this->commonNotIncludes['ar'],
                'basic_info' => [
                    'trip_code' => 'US1234',
                    'days_num' => 10,
                    'destination_name_en' => 'USA East Coast',
                    'destination_name_ar' => 'الساحل الشرقي للولايات المتحدة',
                    'available_to' => '30-12-2024',
                    'double_room_en' => 'Double Room',
                    'double_room_ar' => 'غرفة مزدوجة',
                    'double_room_price' => 4800,
                    'single_room_en' => 'Single Room',
                    'single_room_ar' => 'غرفة فردية',
                    'single_room_price' => 9600,
                    'trip_type_en' => 'International',
                    'trip_type_ar' => 'دولي',
                    'meal_plan_en' => 'Bed & Breakfast',
                    'meal_plan_ar' => 'مبيت وإفطار',
                    'transport_en' => 'Tourist Bus',
                    'transport_ar' => 'حافلة سياحية',
                ],
                'contact_info' => $this->commonContactInfo,
                'payment_methods' => $this->commonPaymentMethods,
            ],

            [
                'title_en' => 'Canada Rocky Mountains Tour',
                'title_ar' => 'جولة جبال روكي الكندية',
                'description_en' => 'Experience the breathtaking beauty of the Canadian Rockies.',
                'description_ar' => 'اختبر الجمال الخلاب لجبال روكي الكندية.',
                'long_description_en' => 'Explore the majestic Canadian Rockies with visits to Banff, Lake Louise, and Jasper. Enjoy stunning mountain views, crystal-clear lakes, and abundant wildlife in this nature lover\'s paradise.',
                'long_description_ar' => 'استكشف جبال روكي الكندية المهيبة مع زيارات إلى بانف وبحيرة لويز وجاسبر. استمتع بإطلالات جبلية خلابة وبحيرات صافية والحياة البرية الوفيرة في هذه الجنة لعشاق الطبيعة.',
                'location_en' => 'Canadian Rockies',
                'location_ar' => 'جبال روكي الكندية',
                'duration_en' => '8 Days',
                'duration_ar' => '٨ أيام',
                'price' => '5200',
                'rating' => 4.9,
                'image' => 'canada.jpg',
                'slug' => 'canada-rockies',
                'region' => 'america',
                'active' => true,
                'features_en' => ['Hotel', 'Breakfast daily', 'Mountain tours', 'Lake cruises', 'Wildlife viewing'],
                'features_ar' => ['فندق', 'إفطار يومي', 'جولات جبلية', 'رحلات بحيرة', 'مشاهدة الحياة البرية'],
                'includes_en' => ['Accommodation', 'Daily breakfast', 'Mountain tours', 'Lake cruises', 'Wildlife viewing tours', 'Professional guide'],
                'includes_ar' => ['الإقامة', 'إفطار يومي', 'جولات جبلية', 'رحلات بحيرة', 'جولات مشاهدة الحياة البرية', 'مرشد محترف'],
                'not_includes_en' => $this->commonNotIncludes['en'],
                'not_includes_ar' => $this->commonNotIncludes['ar'],
                'basic_info' => [
                    'trip_code' => 'CA5678',
                    'days_num' => 8,
                    'destination_name_en' => 'Canadian Rockies',
                    'destination_name_ar' => 'جبال روكي الكندية',
                    'available_to' => '15-10-2024',
                    'double_room_en' => 'Double Room',
                    'double_room_ar' => 'غرفة مزدوجة',
                    'double_room_price' => 5200,
                    'single_room_en' => 'Single Room',
                    'single_room_ar' => 'غرفة فردية',
                    'single_room_price' => 10400,
                    'trip_type_en' => 'International',
                    'trip_type_ar' => 'دولي',
                    'meal_plan_en' => 'Half Board',
                    'meal_plan_ar' => 'نصف إقامة',
                    'transport_en' => 'Coach',
                    'transport_ar' => 'حافلة',
                ],
                'contact_info' => $this->commonContactInfo,
                'payment_methods' => $this->commonPaymentMethods,
            ],
        ];

        foreach ($destinations as $destination) {
            // Ensure slug exists
            if (!isset($destination['slug'])) {
                $destination['slug'] = \Illuminate\Support\Str::slug($destination['title_en']);
            }

            // Ensure active is set
            if (!isset($destination['active'])) {
                $destination['active'] = true;
            }

            // Convert arrays to JSON for storage
            $destination['features_en'] = json_encode($destination['features_en'] ?? []);
            $destination['features_ar'] = json_encode($destination['features_ar'] ?? []);
            $destination['includes_en'] = json_encode($destination['includes_en'] ?? []);
            $destination['includes_ar'] = json_encode($destination['includes_ar'] ?? []);
            $destination['not_includes_en'] = json_encode($destination['not_includes_en'] ?? []);
            $destination['not_includes_ar'] = json_encode($destination['not_includes_ar'] ?? []);
            $destination['basic_info'] = json_encode($destination['basic_info'] ?? []);
            $destination['contact_info'] = json_encode($destination['contact_info'] ?? []);
            $destination['payment_methods'] = json_encode($destination['payment_methods'] ?? []);

            unset($destination['region_ar']);

            TourismDestination::updateOrCreate(
                ['slug' => $destination['slug']],
                $destination
            );
        }
    }
}
